//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

// predefined activities user can choose from for an entry

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "activities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    //     -- maybe at some point i'll implement custom icons, but unicode emoji are fine for now
    //     -- also might add order and categories in the future
    #[sea_orm(column_type = "Text")]
    pub emoji: String,
    #[sea_orm(has_many, via = "piece_4_activities")]
    pub pieces: HasMany<super::piece::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
