//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
// -- small table, mainly to generate ids

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "entries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub datetime: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(has_many)]
    pub pieces: HasMany<super::piece::Entity>,
    pub journal_id: i64,
    #[sea_orm(
        belongs_to,
        from = "journal_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub journal: HasOne<super::journal::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
