//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
// -- small table, mainly to generate ids

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "journal")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(has_many)]
    pub entries: HasMany<super::entries::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
