//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod activities;
pub mod blobs;
pub mod entries;
pub mod journal;
pub mod piece;
pub mod piece_0_text;
pub mod piece_1_mood;
pub mod piece_2_blob;
pub mod piece_3_location;
pub mod piece_4_activities;
pub mod settings;
