//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

// -- simple block of text
#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "piece_0_text")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub piece_id: i64,
    pub title: Option<String>,
    pub content: String,
    #[sea_orm(
        belongs_to,
        from = "piece_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub piece: HasOne<super::piece::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
