//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

// large unparsable file: image, audio, video
#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "piece_2_blob")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    // 0 = image, 1 = audio, 2 = video
    pub r#type: i64,
    #[sea_orm(column_type = "Blob")]
    pub data: Vec<u8>,
    #[sea_orm(
        belongs_to,
        from = "id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub piece: HasOne<super::piece::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
