//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

// core table, each entry can have multiple pieces
#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "piece")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub entry_id: i64,
    // -- 0 = text, 1 = mood, 2 = blob, 3 = location, 4 = activities
    pub piece_type: i64,
    #[sea_orm(
        belongs_to,
        from = "entry_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub entries: HasOne<super::entries::Entity>,
    #[sea_orm(has_one)]
    pub piece_0_text: HasOne<super::piece_0_text::Entity>,
    #[sea_orm(has_one)]
    pub piece_1_mood: HasOne<super::piece_1_mood::Entity>,
    #[sea_orm(has_one)]
    pub piece_2_blob: HasOne<super::piece_2_blob::Entity>,
    #[sea_orm(has_one)]
    pub piece_3_location: HasOne<super::piece_3_location::Entity>,
    #[sea_orm(has_many)]
    pub piece_4_activity: HasMany<super::piece_4_activities::Entity>,
    #[sea_orm(has_many, via = "piece_4_activities")]
    pub activities: HasMany<super::activities::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
