//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

// user rates mood on two scales: pleasantness and energy
#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "piece_1_mood")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,

    //  integers are fucky, and 30 bits per entry doesnt matter. f64: -1 to 1, just like apple
    #[sea_orm(column_type = "Double")]
    pub pleasantness: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub energy: Option<f64>,
    #[sea_orm(
        belongs_to,
        from = "id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub piece: HasOne<super::piece::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
