//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

// -- this table is unique because the rows are many : 1 piece
// -- a mapping of per piece, per activity, the value for the activity (eg 0 = not done, 1 = done)
// -- very intentionally NOT a table with 1 column per activity, because the user can update the list of activities, and schema changes are expensive

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "piece_4_activities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub activity_id: i64,
    // sqlite doesnt distinguish between int and bool, and i might want to add int support in the future, so int is fine
    pub value: i64,
    #[sea_orm(
        belongs_to,
        from = "activity_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub activities: HasOne<super::activities::Entity>,
    #[sea_orm(
        belongs_to,
        from = "id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub piece: HasOne<super::piece::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
