//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

// key-value store for settings
#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "settings")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        ignore,
        column_type = "custom(\"string\")",
        select_as = "text"
    )]
    pub key: String,
    #[sea_orm(ignore, column_type = "custom(\"ANY\")", select_as = "text", nullable)]
    pub value: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
