[application]
name = "PowerJournal"

[web.app]

# HTML title tag content
title = "PowerJournal"

[bundle]
identifier = "me.machineonamission.powerjournal"
publisher = "Machine on a Mission"

[bundle.windows]
webview_install_mode = { EmbedBootstrapper = { silent = true } }