#![feature(try_blocks)]

use crate::database::entity::prelude::*;
use crate::database::init_db;
use anyhow::{anyhow, Context, Error, Result};
use chrono::{Local, NaiveDate, TimeZone};
use glam::DVec3;
use lightningcss::properties::Property;
use lightningcss::stylesheet::{ParserOptions, StyleAttribute};
use lightningcss::values::color::CssColor;
use scraper::{Html, Selector};
use sea_orm::{ActiveModelTrait, Set};
use sea_orm::{ActiveValue, TransactionTrait};
use serde::{Deserialize, Serialize};
use std::fmt::Debug;
use std::fs;
use std::io::{Read, Seek};
use zip::ZipArchive;

fn selector(s: &str) -> Result<Selector> {
    Selector::parse(s).map_err(|e| anyhow!("{e:?}"))
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(rename_all = "camelCase")]
struct Location {
    longitude: f64,
    city: String,
    type_of_place: Option<String>,
    latitude: f64,
    place_name: String,
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(rename_all = "camelCase")]
struct LocationSidecar {
    visits: Vec<Location>,
}

/// THIS FUNCTION WAS WRITTEN BY GEMINI
pub fn calculate_mood_valence(point: (f64, f64, f64)) -> f64 {
    // see https://github.com/machineonamission/applejournalmoodcolors
    let p = DVec3::from(point);

    let gvertices = [
        DVec3::new(254.96, 238.04, 230.99),
        DVec3::new(248.67, 219.51, 177.07),
        DVec3::new(214.55, 233.19, 179.14),
        DVec3::new(225.79, 230.95, 231.47),
        DVec3::new(215.30, 223.77, 235.97),
        DVec3::new(229.34, 235.03, 255.33),
        DVec3::new(217.02, 209.98, 243.02),
    ];

    let valences = [1.0, 2.0 / 3.0, 1.0 / 3.0, 0.0, -1.0 / 3.0, -2.0 / 3.0, -1.0];

    gvertices
        .windows(2) // Iterate over adjacent pairs of points (segments)
        .zip(valences.windows(2)) // Pair them with their corresponding valences
        .map(|(v_win, val_win)| {
            let (a, b) = (v_win[0], v_win[1]);
            let (val_a, val_b) = (val_win[0], val_win[1]);

            // Direction vector of the segment, and vector from 'a' to our point
            let dir = b - a;
            let w = p - a;

            // Project point onto the segment line.
            // We clamp between 0.0 and 1.0 to ensure it falls strictly within the segment endpoints.
            let t = (w.dot(dir) / dir.length_squared()).clamp(0.0, 1.0);

            // Calculate exact squared distance from the input point to this segment
            let closest_point_on_segment = a + dir * t;
            let dist_sq = p.distance_squared(closest_point_on_segment);

            // Interpolate the valence based on 't'
            let valence = val_a + t * (val_b - val_a);

            (dist_sq, valence)
        })
        // Find the segment that is mathematically closest to the input point
        .min_by(|a, b| a.0.total_cmp(&b.0))
        .unwrap() // Unwrap is safe here as there are guarantees of valid floats & length > 0
        .1 // Return just the valence
}

/// WRITTEN BY GEMINI
/// Parses a date string like "Thursday, January 3, 2019" into a Unix timestamp
/// (seconds since the UNIX epoch) in the system's local timezone.
pub fn parse_date_to_unix_timestamp(date_str: &str) -> Result<i64> {
    // 1. Define the format string matching your input
    // %A = Full weekday name (Thursday)
    // %B = Full month name (January)
    // %d = Day of the month (3)
    // %Y = 4-digit year (2019)
    let format = "%A, %B %d, %Y";

    // 2. Parse the string into a NaiveDate (a date without time or timezone)
    let naive_date = NaiveDate::parse_from_str(date_str, format)?;

    // 3. Give it a time so we can convert it to a timestamp (assuming noon)
    // and_hms_opt takes (hour, minute, second)
    let naive_datetime = naive_date.and_hms_opt(12, 0, 0).context("hms opt fail")?;

    // 4. Bind it to the Local timezone
    // We use .earliest() to handle potential Daylight Saving Time edge cases
    // (e.g., if a DST shift happens exactly at midnight, making the time ambiguous)
    let local_datetime = Local
        .from_local_datetime(&naive_datetime)
        .earliest()
        .context("Failed to map local time due to timezone ambiguity")?;

    // 5. Extract the Unix timestamp (seconds since Jan 1, 1970)
    Ok(local_datetime.timestamp())
}

pub async fn import_apple_journal<R: Read + Seek + Debug>(file: R) -> Result<()> {
    /// file must be file-like object representing an Apple Journal export
    /// - 3 dots in the top right of the Journal app > Export
    /// - once it's exported to a folder, open the files app
    /// - long press AppleJournalEntries > Compress
    /// use the zip file generated by this!
    println!("beginning import");
    // parse zip
    let mut masterzip = ZipArchive::new(file)?;

    // init db
    let db = init_db().await?;
    let txn = db.begin().await?;

    // some selectors we use for html
    let assets_s = selector(".assetGrid")?;
    let item_s = selector(".gridItem")?;
    let photo_s = selector(".assetType_photo")?;
    let video_s = selector(".assetType_video, .assetType_audio")?;
    let som_s = selector(".assetType_stateOfMind")?;
    let location_s = selector(".assetType_multiPinMap")?;
    let date_s = selector(".pageHeader")?;

    let title_s = selector(".title")?;
    let body_s = selector(".bodyText")?;

    let img = selector("img")?;
    let source = selector("source")?;

    let mut import_journal = journal::ActiveModel::builder().set_title("Apple Journal Import");

    // for every file in the zip
    for i in 0..masterzip.len() {
        // read file contents if it is an entry
        // inside block because getting a ZipFile object is a mutable borrow on masterzip,
        // and you can only do one of those at a time, so we gotta let file go out of scope
        let mut buf: String = String::new();
        {
            let mut file = masterzip.by_index(i)?;
            let path = file.enclosed_name().context("zip enclosed name error")?;
            if !path.starts_with("AppleJournalEntries/Entries") || file.is_dir() {
                continue;
            }
            println!("entry {:?}", &path);
            file.read_to_string(&mut buf)?;
        }
        // for every entry in the zip:

        // init entry db object
        let mut master_entry = entries::ActiveModel::builder();
        // .set_datetime(entry.datetime / 1000) // daylio does ms, i do s like a NORMAL PERSON
        // .set_title(entry.note_title.clone());

        let document = Html::parse_document(&*buf);

        // parse datetime
        let dt_str = document.select(&date_s).next().context("date fail")?;
        let dt = parse_date_to_unix_timestamp(dt_str.text().collect::<String>().as_str())?;
        master_entry = master_entry.set_datetime(dt);

        // title
        let title = document.select(&title_s).next();
        if let Some(title) = title {
            let title_text = title.text().collect::<String>();
            master_entry = master_entry.set_title(title_text);
        }

        // body content
        let body = document.select(&body_s).next();
        if let Some(body) = body {
            let body_contents = body.html();
            master_entry =
                master_entry.add_piece(piece::ActiveModel::builder().set_piece_0_text(
                    piece_0_text::ActiveModel::builder().set_content(body_contents),
                ).set_piece_type(0));
        } else {
            println!("no body found");
        }

        // grid is where apple journal stores "assets", basically pieces for us
        let grid = document.select(&assets_s).next().context("grid fail")?;

        // handle blob assets (img, video, audio)
        let mut asset_srcs: Vec<&str> = vec![];

        // because its html, photos are img and video/audio is source

        // get images from img
        for element in grid.select(&photo_s) {
            let img = element.select(&img).next().context("img fail")?;
            let src = img.value().attr("src").context("src fail")?;
            asset_srcs.push(src);
        }

        // get media from video/audio
        for element in grid.select(&video_s) {
            let source = element.select(&source).next().context("source fail")?;
            let src = source.attr("src").context("src fail")?;
            asset_srcs.push(src);
        }

        // for each asset, get the blob data from the zip and add it to the entry
        for src in asset_srcs {
            let path = format!("AppleJournalEntries/Entries/{src}");
            let canon_path = path_clean::clean(path);
            dbg!(&canon_path);
            let mut buf: Vec<u8> = Vec::new();

            {
                let mut file = masterzip.by_path(canon_path)?;
                file.read_to_end(&mut buf)?;
            }
            // add piece with blob
            master_entry = master_entry.add_piece(
                piece::ActiveModel::builder().set_piece_2_blob(
                    piece_2_blob::ActiveModel::builder()
                        .set_data(buf)
                        .set_blob_type(0), // assume they're all images for now
                ).set_piece_type(2),
            )
        }
        
        // mood/"state of mind"
        for element in grid.select(&som_s) {
            // the best mood data we have is the css background color so uh
            // parse out of html
            let color = element.value().attr("style");

            if let Some(color) = color {
                // parse out of css declaration
                let options = ParserOptions::default();
                if let Ok(style) = StyleAttribute::parse(color, options) {
                    // 2. Iterate through all standard CSS declarations in the style tag
                    for declaration in style.declarations.declarations {
                        // 3. Pattern match exactly on the BackgroundColor property
                        if let Property::BackgroundColor(color) = declaration {
                            let rgb = color
                                .to_rgb()
                                .map_err(|e| anyhow!("Failed to convert color to RGB: {:?}", e))?;
                            // 4. Extract the RGBA values from the color enum
                            if let CssColor::RGBA(rgba) = rgb {
                                // calculate valence from rgb
                                let valence = calculate_mood_valence((
                                    rgba.red as f64,
                                    rgba.green as f64,
                                    rgba.blue as f64,
                                ));
                                dbg!(&rgba, &valence);
                                // add to entry
                                master_entry = master_entry.add_piece(
                                    piece::ActiveModel::builder().set_piece_1_mood(
                                        piece_1_mood::ActiveModel::builder()
                                            .set_pleasantness(valence),
                                    ).set_piece_type(1),
                                );
                            }
                        }
                    }
                }
            }
        }
        
        // locations
        for element in grid.select(&location_s) {
            // grab its ID, there's a corresponding .json file with the actual data in it!
            let id = element.value().attr("id").context("id fail")?;
            let mut buf: String = String::new();
            {
                let mut scfile =
                    masterzip.by_path(format!("AppleJournalEntries/Resources/{id}.json"))?;
                scfile.read_to_string(&mut buf)?;
            }

            let json: LocationSidecar = serde_json::from_str(&*buf)?;
            for visit in json.visits {
                master_entry = master_entry.add_piece(
                    piece::ActiveModel::builder().set_piece_3_location(
                        piece_3_location::ActiveModel::builder()
                            .set_lat(visit.latitude)
                            .set_lon(visit.longitude)
                            .set_name(visit.place_name)
                    ).set_piece_type(3),
                );
            }

        }
        // master_entry.insert(&txn).await?;
        import_journal = import_journal.add_entry(master_entry);
    }
    import_journal.insert(&txn).await?;

    txn.commit().await?;
    println!("finished!");
    Ok(())
}

pub async fn main() {
    println!("debug: loading zip");
    import_apple_journal(fs::File::open("ignore/AppleJournalEntries.zip").expect("file open error"))
        .await
        .unwrap()
}
