use crate::Route;
use crate::components::progress::Progress;
use crate::importers::common::ImporterArgs;
use crate::importers::powerjournal::import_powerjournal;
use crate::importers::{applejournal, daylio};
use bytes::Bytes;
use dioxus::prelude::*;
use sea_orm::DatabaseConnection;
use std::pin::Pin;

// so the Bytes object just HAPPENS to be what Dioxus file uploads are. so fucking, whatever. its a fine object for this.
type ImportFuture<'a> = Pin<Box<dyn Future<Output = anyhow::Result<()>> + 'a>>;
type ImportFn = for<'a> fn(ImporterArgs<'a>) -> ImportFuture<'a>;

#[derive(Clone, Debug, PartialEq, Copy)]
pub struct Importer {
    pub name: &'static str,
    pub function: ImportFn,
    pub docs: fn() -> Element,
}

/// The Home page component that will be rendered when the current route is `[Route::Home]`
#[component]
pub fn ImportersView() -> Element {
    let IMPORTERS: [Importer; 3] = [
        Importer {
            name: "PowerJournal",
            function: |args| Box::pin(import_powerjournal(args)),
            docs: || {
                rsx! {
                    p { "NOT IMPLEMENTED. Placeholder UI." }
                }
            },
        },
        Importer {
            name: "Daylio",
            function: |args| Box::pin(daylio::import_daylio(args)),
            docs: || {
                rsx! {
                    p { "This importer takes a .daylio BACKUP file" }
                    p { "This will import entries, moods, files, activities." }
                    h2 { "Instructions" }
                    ul {
                        li { "In the Daylio app: More > Backup & Restore > Advanced Options > Export" }
                        li { "This will save a .daylio file to your device, upload it below." }
                    }
                }
            },
        },
        Importer {
            name: "Apple Journal",
            function: |args| Box::pin(applejournal::import_apple_journal(args)),
            docs: || {
                rsx! {
                    p { "This importer takes a .zip of an Apple Journal Export." }
                    h2 { "Instructions" }
                    ul {
                        li { "Open Apple Journal" }
                        li { "3 dots in the top right of the Journal app > Export" }
                        li { "save the folder" }
                        li { "once it's exported to a folder, open the files app" }
                        li { "long press the exported AppleJournalEntries folder > Compress" }
                        li { "upload the zip file generated by this below:" }
                    }
                }
            },
        },
    ];
    let a = rsx! {};
    let mut log = use_signal(Vec::<String>::new);
    let mut max_prog = use_signal(|| 0i64);
    let mut current_prog = use_signal(|| 0i64);
    let mut selection = use_signal(|| Option::<usize>::None);
    let selected_importer: Memo<Option<Importer>> = use_memo(move || {
        if let Some(selected) = selection() {
            Some(IMPORTERS[selected])
        } else {
            None
        }
    });
    let mut file = use_signal(|| Option::<Bytes>::None);

    let db_signal = use_context::<Resource<DatabaseConnection>>();

    // runs after every render where `log` changed
    use_effect(move || {
        log.read(); // subscribe to changes
        spawn(async move {
            // scroll to bottom if user is near bottom
            let _ = document::eval(
                r#"
                let el = document.getElementById("log_pre");
                if (el) {
                    el.scrollTop = el.scrollHeight;
                }
            "#,
            )
            .await;
        });
    });

    rsx! {
        div {
            display: "flex",
            flex_direction: "column",
            height: "100vh",
            h1 {
                "Journal Importer"
            }
            form {
                for (i, importer) in IMPORTERS.iter().enumerate() {
                    div {
                        class: "form-check",
                        input {
                            class: "form-check-input",
                            r#type: "radio",
                            name: "importer",
                            id: "{importer.name}",
                            oninput: move |evt| {
                               selection.set(Some(i));
                            },
                        }
                        label {
                            class: "form-check-label",
                            r#for: "{importer.name}",
                            "{importer.name}"
                        }
                    }
                }
                if let Some(selected) = selected_importer() {
                    div {
                        {(selected.docs)()}
                    }
                    input {
                        // tell the input to pick a file
                        type: "file",
                        // list the accepted extensions
                        accept: "*",
                        // pick multiple files
                        multiple: false,
                        onchange: move |evt| async move {
                            let files = evt.files();
                            if files.len() > 0 {
                                let bytes = files[0].read_bytes().await.unwrap();
                            file.set(Some(bytes))
                            }

                        }
                    }
                    if file().is_some() {
                        button {
                            r#type: "button",
                            class: "btn btn-primary",
                            onclick: move |_| async move {
                                let db = db_signal().unwrap();
                                let args = ImporterArgs {
                                    file: file().unwrap(),
                                    db: &db,
                                    log_signal: log,
                                    current_prog_signal: current_prog,
                                    max_prog_signal: max_prog,
                                };
                                selected.function.call((args,)).await.unwrap();
                            },
                            "Import"
                        }
                    }
                }
                // show the docs for the selected importer
            }
            // TODO: scroll to bottom
            if !log().is_empty() {
                Progress {
                    max: max_prog,
                    current: current_prog,
                }
                h2 {"Log:"}
                pre {
                    id: "log_pre",
                    flex_grow: 1,
                    overflow: "scroll",
                    background: "black",
                    for line in log() {
                        code {
                            "{line}\n"
                        }
                    }
                }
            }
        }
    }
}
