use std::pin::Pin;
use bytes::Bytes;
use dioxus::prelude::*;
use sea_orm::DatabaseConnection;
use crate::importers::{daylio, applejournal};
use crate::Route;

// so the Bytes object just HAPPENS to be what Dioxus file uploads are. so fucking, whatever. its a fine object for this.
type ImportFuture<'a> = Pin<Box<dyn Future<Output = anyhow::Result<()>> + 'a>>;
type ImportFn = for<'a> fn(Bytes, &'a DatabaseConnection, Signal<Vec<String>>) -> ImportFuture<'a>;

#[derive(Clone, Debug, PartialEq, Copy)]
pub struct Importer {
    pub name: &'static str,
    pub function: ImportFn,
    pub docs: fn() -> Element
}

/// The Home page component that will be rendered when the current route is `[Route::Home]`
#[component]
pub fn ImportersView() -> Element {
    let IMPORTERS: [Importer; 2] = [
        Importer {
            name: "Daylio",
            function: |file, db, log| Box::pin(daylio::import_daylio(file, db, log)),
            docs: || rsx! {
                p { "This importer takes a .daylio BACKUP file" }
                p { "This will import entries, moods, files, activities." }
                h2 { "Instructions" }
                ul {
                    li { "In the Daylio app: More > Backup & Restore > Advanced Options > Export" }
                    li { "This will save a .daylio file to your device, upload it below." }
                }
            },
        },
        Importer {
            name: "Apple Journal",
            function: |file, db, log| Box::pin(applejournal::import_apple_journal(file, db, log)),
            docs: || rsx! {
                p { "This importer takes a .zip of an Apple Journal Export." }
                h2 { "Instructions" }
                ul {
                    li { "Open Apple Journal" }
                    li { "3 dots in the top right of the Journal app > Export" }
                    li { "save the folder" }
                    li { "once it's exported to a folder, open the files app" }
                    li { "long press the exported AppleJournalEntries folder > Compress" }
                    li { "upload the zip file generated by this below:" }
                }
            },
        },
    ];
    let a = rsx! {};
    let mut log = use_signal(Vec::<String>::new);
    let mut selection = use_signal(|| Option::<usize>::None);
    let selected_importer: Memo<Option<Importer>> = use_memo(move || {
        if let Some(selected) = selection() {
            Some(IMPORTERS[selected])
        } else {
            None
        }
    });
    let mut file = use_signal(|| Option::<Bytes>::None);

    let db_signal = use_context::<Resource<DatabaseConnection>>();
    rsx! {
        h1 {
            "3rd-party Journal Importer"
        }
        form {
            for (i, importer) in IMPORTERS.iter().enumerate() {
                div {
                    class: "form-check",
                    input {
                        class: "form-check-input",
                        r#type: "radio",
                        name: "importer",
                        id: "{importer.name}",
                        oninput: move |evt| {
                           selection.set(Some(i));
                        },
                    }
                    label {
                        class: "form-check-label",
                        r#for: "{importer.name}",
                        "{importer.name}"
                    }
                }
            }
            if let Some(selected) = selected_importer() {
                div {
                    {(selected.docs)()}
                }
                input {
                    // tell the input to pick a file
                    type: "file",
                    // list the accepted extensions
                    accept: "*",
                    // pick multiple files
                    multiple: false,
                    onchange: move |evt| async move {
                        let bytes = evt.files()[0].read_bytes().await.unwrap();
                        file.set(Some(bytes))
                    }
                }
                if file().is_some() {
                    button {
                        r#type: "button",
                        class: "btn btn-primary",
                        onclick: move |_| async move {
                            let db = db_signal().unwrap();
                            selected.function.call((file().as_ref().unwrap().clone(), &db, log)).await.unwrap();
                        },
                        "Import"
                    }
                }
                div {
                    for line in log() {
                       p { "{line}" }
                    }
                }
            }
            // show the docs for the selected importer
        }
    }
}
