import { Button, VerticalBox, ScrollView, Spinner } from "std-widgets.slint";


component Piece {
    height: 100px;
    width: 100px;
    Rectangle {
        width: la.width;
        height: la.height;
        x: la.x;
        y: la.y;
        background: darkgray;
        border-radius: 10px;
    }

    la := VerticalLayout {
        padding: 10px;
        Text {
            text: "piece of data";
            font-size: 12px;
        }
    }
}

component Entry {
    Rectangle {
        width: la.width;
        height: la.height;
        x: la.x;
        y: la.y;
        background: gray;
        border-radius: 10px;
    }

    la := VerticalLayout {
        padding: 10px;
        Text {
            text: "Title";
            font-size: 24px;
        }

        Text {
            text: "body body body";
            font-size: 12px;
        }

        ScrollView {
            height: 110px;
            HorizontalLayout {
                padding: 5px;
                spacing: 5px;
                Piece { }

                Piece { }

                Piece { }

                Piece { }

                Piece { }

                Piece { }

                Piece { }
            }
        }
    }
}

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    ScrollView {
        width: parent.width;
        height: parent.height;
        VerticalLayout {
            alignment: start;
            padding: 10px;
            spacing: 10px;
            Entry { }

            Entry { }

            Entry { }

            Entry { }
        }
    }
}
